name: recpt1 build test

on:
  push:
    branches: [ "master" ]
    paths:
      - 'recpt1/**'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

defaults:
  run:
    working-directory: recpt1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: pwd
      run: pwd
    - name: Create a temporary device file
      run: |
        sudo mknod /dev/pt1video0 c 235 0
        sudo mknod /dev/pt1video1 c 235 1
        sudo mknod /dev/pt1video2 c 235 2
        sudo mknod /dev/pt1video3 c 235 3
        sudo chmod a+rw /dev/pt1video0
        sudo chmod a+rw /dev/pt1video1
        sudo chmod a+rw /dev/pt1video2
        sudo chmod a+rw /dev/pt1video3
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
