name: release

on:
  push:
    tags:
      - 'v*'
    workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # コンパイラーをインストールする
      # 参照：https://github.com/macaron/recpt1-static-build
      - name: Install Compiler
        working-directory: /usr/local/bin
        run: |
          wget https://musl.libc.org/releases/musl-1.2.4.tar.gz
          tar -xvf musl-1.2.4.tar.gz
          cd musl-1.2.4
          ./configure --prefix=$HOME/musl --exec-prefix=$HOME --syslibdir=$HOME/musl/lib
          make -j$(nproc)
          make install
          echo "$HOME/bin" >> $GITHUB_PATH

      # recpt1をビルドし、ZIPファイルにまとめる
      - name: Build for recpt1
        working-directory: recpt1
        run: |
          sudo apt install -y --no-install-recommends autoconf automake
          ./autogen.sh
          ./configure CC=musl-gcc --enable-b25
          make
          zip release.zip recpt1 recpt1ctl checksignal

      # タグ名を取得する
      - name: Set_version
        id: set_version
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      # タグが push された場合のみ実行される
      - name: create_release
        uses: shogo82148/actions-create-release@v1
        id: create_release # ファイルアップロードに outputs の値を使用するため ID が必要
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_version.outputs.version }}
          release_name: recpt1 ${{ steps.set_version.outputs.version }} Release
          body: |
            リリースの作成テストです。
            下書きかつプレリリースの状態で作成されます。
          # 下書き状態で作成する場合は true (省略時 false)
          draft: true
          # プレリリース表示を付ける場合は true (省略時 false)
          prerelease: true

      # タグが push された場合のみ実行される
      - name: upload_release_asset
        uses: shogo82148/actions-upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # リリースのアップロード URL (必須)
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # 添付ファイルのパス (必須)
          asset_path: ./release.zip
          # 添付ファイルの表示名 (必須)
          asset_name: recpt1-${{ steps.set_version.outputs.version }}.zip
          # 添付ファイルに対応する content-type (必須)
          asset_content_type: application/zip
