name: release

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
    workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # ビルド処理に置き換える
      - run: |
          touch release
          zip release.zip release

      # タグが push された場合のみ実行される
      - name: create_release
        uses: actions/create-release@master
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: recpt1 ${{ github.ref }} Release
          body: |
            リリースの作成テストです。
            下書きかつプレリリースの状態で作成されます。
          draft: true
          prerelease: true

      # タグが push された場合のみ実行される
      - name: upload-release-asset
        uses: actions/upload-release-asset@master
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: recpt1-${{ github.ref }}.zip
          asset_content_type: application/zip
